world_identifier = [u'world']
robot_identifier = world_identifier + [u'robot']
fk_identifier = robot_identifier + [u'get_fk']
js_identifier = robot_identifier + [u'joint_state']
data_folder_identifier = [u'asdf']

cartesian_goal_identifier = [u'goal']
trajectory_identifier = [u'traj']
time_identifier = [u'time']
next_cmd_identifier = [u'motor']
closest_point_identifier = [u'cpi']
collision_goal_identifier = [u'collision_goal']
soft_constraint_identifier = [u'soft_constraints']
default_joint_weight_identifier = [u'default_joint_weight']
default_joint_vel_identifier = [u'default_joint_vel']
