# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Building Giskard in ROS Docker
        run: |
          docker pull osrf/ros:melodic-desktop-full
          wget -q -O build.sh https://raw.githubusercontent.com/tlipps/giskardpy/devel/entrypoints/buildMelodic.sh
          wget -q -O test.sh https://raw.githubusercontent.com/tlipps/giskardpy/devel/entrypoints/test.sh
          wget -q -O Dockerfile https://raw.githubusercontent.com/tlipps/giskardpy/devel/Dockerfiles/DockerfileMelodic
          docker build . --file Dockerfile --no-cache=True --tag giskard_docker:latest
          
      - name: Testing Giskard in ROS Docker
        run: |
          docker run -dit giskard_docker:latest bash
          echo "CONTAINER_ID=$(sudo docker ps)"
          echo "CONTAINER_ID=$(sudo docker ps -aqf "status=running")"
          echo "CONTAINER_ID=$(sudo docker ps -aqf "status=running")" >> $GITHUB_ENV
          docker exec -dit $(sudo docker ps -aqf "status=running") bash -c "echo test;"
          docker exec -dit $(sudo docker ps -aqf "status=running") bash -c "source ~/ros_ws/devel/setup.bash; roslaunch iai_kitchen upload_kitchen_obj.launch;"
          docker exec -dit $(sudo docker ps -aqf "status=running") bash -c "source ~/ros_ws/devel/setup.bash; roslaunch iai_pr2_sim ros_control_sim_with_base.launch;"
          docker exec -it $(sudo docker ps -aqf "status=running") "./test.sh;"
      
      # Runs a set of commands using the runners shell
      - name: Finished
        run: echo Done
