name: Trigger giskardpy_ros ros2-jazzy-main Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger_giskardpy_ros:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in giskardpy_ros
        run: |
          RESPONSE=$(curl -L -w "%{http_code}\\n"\
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.giskardpy_ros_test_trigger }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/giskardpy_ros/actions/workflows/ci_standalone.yml/dispatches \
            -d '{"ref":"ros2-jazzy-main"}')

          # Extract the response body and HTTP status code from the response
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)

          if [[ "$HTTP_STATUS" -eq 204 ]]; then
            echo "Successfully triggered giskardpy_ros workflow. Status Code: $HTTP_STATUS"
          else
            echo "Failed to trigger giskardpy_ros workflow. Status Code: $HTTP_STATUS"
            echo "$RESPONSE" | sed '$d'
            exit 1
          fi