name: Trigger giskardpy_ros ros1-noetic-main Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - giskard_library
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  trigger_giskardpy_ros_ci_standalone:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["ros1-noetic-main", "ros2-jazzy-main"]
    steps:
      # Triggers ci_standalone workflow of giskardpy_ros repo. Needs setup secret token to work
      - name: Trigger workflow in giskardpy_ros
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            DATA='{
              "ref":"${{ matrix.branch }}",
              "inputs": {
                "is_trigger": true,
                "pr_id": "${{ github.event.pull_request.number }}"
              }
            }'
          else
            DATA='{
              "ref":"${{ matrix.branch }}"
            }'
          fi
          
          RESPONSE=$(curl -L -w "%{http_code}\\n" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.giskardpy_ros_test_trigger }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/giskardpy_ros/actions/workflows/ci_standalone.yml/dispatches \
            -d "$DATA")

          # Extract the response body and HTTP status code from the response
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)

          if [[ "$HTTP_STATUS" -eq 204 ]]; then
            echo "Successfully triggered giskardpy_ros workflow. Status Code: $HTTP_STATUS"
          else
            echo "Failed to trigger giskardpy_ros workflow. Status Code: $HTTP_STATUS"
            echo "$RESPONSE" | sed '$d'
            exit 1
          fi